import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pi_qbank/widgets/custom_app_bar.dart';
import 'package:pi_qbank/pages/mcq_test_page.dart';
import 'package:pi_qbank/pages/short_question_page.dart';
import 'dart:convert';

class JsonToTestMakerPage extends StatefulWidget {
  const JsonToTestMakerPage({super.key});

  @override
  State<JsonToTestMakerPage> createState() => _JsonToTestMakerPageState();
}

class _JsonToTestMakerPageState extends State<JsonToTestMakerPage> with TickerProviderStateMixin {
  final TextEditingController _jsonController = TextEditingController();
  final TextEditingController _countController = TextEditingController(text: '10');
  String _selectedTestType = 'MCQ';
  String _selectedLanguage = 'বাংলা';
  
  late AnimationController _animationController;
  late Animation<double> _fadeAnimation;
  late Animation<Offset> _slideAnimation;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      duration: const Duration(milliseconds: 600),
      vsync: this,
    );
    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _animationController, curve: Curves.easeInOut),
    );
    _slideAnimation = Tween<Offset>(
      begin: const Offset(0, 0.2),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _animationController,
      curve: Curves.easeOutBack,
    ));
    _animationController.forward();
  }

  @override
  void dispose() {
    _animationController.dispose();
    _jsonController.dispose();
    _countController.dispose();
    super.dispose();
  }

  String _getCustomInstruction() {
    final int count = int.tryParse(_countController.text) ?? 10;
    final String countText = 'Generate exactly $count questions.';
    if (_selectedTestType == 'MCQ') {
      return '''Analyze the provided image and $countText
Language: $_selectedLanguage
Format:
{
  "questions": [
    {
      "question": "Question text?",
      "options": {
        "A": "Option 1",
        "B": "Option 2",
        "C": "Option 3",
        "D": "Option 4"
      },
      "correct_answer": "A"
    }
  ]
}''';
    } else if (_selectedTestType == 'Short Question') {
      return '''Analyze the provided image and $countText
Language: $_selectedLanguage
Format:
{
  "questions": [
    {
      "question": "Question text?",
      "answer": "Correct answer"
    }
  ]
}''';
    } else {
      return '''Analyze the provided image and $countText
Language: $_selectedLanguage
Format:
{
  "questions": [
    {
      "question_number": 1,
      "stem": "Stem text or passage...",
      "sub_questions": [
        {"label": "ক", "text": "Knowledge based question", "marks": 1},
        {"label": "খ", "text": "Comprehension based question", "marks": 2},
        {"label": "গ", "text": "Application based question", "marks": 3},
        {"label": "ঘ", "text": "Higher order thinking question", "marks": 4}
      ]
    }
  ]
}''';
    }
  }
  void _copyToClipboard() {
    Clipboard.setData(ClipboardData(text: _getCustomInstruction()));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('Custom instruction copied to clipboard!'),
        backgroundColor: Colors.teal.shade600,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  Future<void> _pasteFromClipboard() async {
    ClipboardData? data = await Clipboard.getData('text/plain');
    if (data != null && data.text != null) {
      if (!mounted) return;
      setState(() {
        _jsonController.text = data.text!;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Text pasted from clipboard'),
          backgroundColor: Colors.teal.shade600,
          behavior: SnackBarBehavior.floating,
          duration: const Duration(seconds: 1),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
      );
    }
  }

  void _buildTest() {
    final String jsonText = _jsonController.text.trim();
    if (jsonText.isEmpty) {
      _showError('Please paste the JSON generated by the third-party app.');
      return;
    }

    try {
      final decoded = json.decode(jsonText);
      final questions = decoded['questions'] as List?;
      
      if (questions == null || questions.isEmpty) {
        _showError('Invalid JSON format: "questions" list is missing or empty.');
        return;
      }

      if (_selectedTestType == 'MCQ') {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => MCQTestPage(
              numberOfQuestions: questions.length,
              testTimeInMinutes: 10, // Default time
              aiResponse: jsonText,
              language: _selectedLanguage,
            ),
          ),
        );
      } else if (_selectedTestType == 'Short Question') {
        // For Short Questions, we need to convert JSON to the text format expected by ShortQuestionPage
        String formattedResponse = '';
        for (int i = 0; i < questions.length; i++) {
          final q = questions[i];
          formattedResponse += '${i + 1}. ${q['question']}\nউত্তর: ${q['answer']}\n\n';
        }

        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => ShortQuestionPage(
              numberOfQuestions: questions.length,
              testTimeInMinutes: 10,
              aiResponse: formattedResponse,
              language: _selectedLanguage,
            ),
          ),
        );
      } else {
        // For Creative Questions
        _showCreativeQuestionsDialog(questions);
      }
    } catch (e) {
      _showError('Failed to parse JSON: ${e.toString()}');
    }
  }

  void _showCreativeQuestionsDialog(List questions) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Generated Creative Questions'),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView.builder(
            shrinkWrap: true,
            itemCount: questions.length,
            itemBuilder: (context, index) {
              final q = questions[index];
              final subQs = q['sub_questions'] as List;
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('${q['question_number']}. ${q['stem']}', style: const TextStyle(fontWeight: FontWeight.bold)),
                  ...subQs.map((sq) => Text('${sq['label']}) ${sq['text']} (${sq['marks']})')),
                  const Divider(),
                ],
              );
            },
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Close')),
        ],
      ),
    );
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red.shade600,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade50,
      appBar: CustomAppBar(
        title: 'Json to Test Maker',
        centerTitle: true,
      ),
      body: FadeTransition(
        opacity: _fadeAnimation,
        child: SlideTransition(
          position: _slideAnimation,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(20.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                _buildHeader(),
                const SizedBox(height: 24),
                _buildConfigSection(),
                const SizedBox(height: 24),
                _buildInstructionSection(),
                const SizedBox(height: 24),
                _buildInputSection(),
                const SizedBox(height: 32),
                _buildActionButton(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Colors.teal.shade600, Colors.teal.shade800],
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.teal.withOpacity(0.3),
            blurRadius: 15,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        children: [
          const Icon(Icons.code_outlined, size: 48, color: Colors.white),
          const SizedBox(height: 16),
          const Text(
            'Json to Test Maker',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 8),
          Text(
            'Paste JSON generated from images using AI to create tests instantly',
            style: TextStyle(
              fontSize: 14,
              color: Colors.white.withOpacity(0.9),
              height: 1.4,
            ),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }

  Widget _buildConfigSection() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Step 1: Configure Test Type',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 16),
          _buildDropdown(
            label: 'Test Type',
            icon: Icons.quiz_outlined,
            value: _selectedTestType,
            items: ['MCQ', 'Short Question', 'Creative Question'],
            onChanged: (val) => setState(() => _selectedTestType = val!),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: _buildDropdown(
                  label: 'Language',
                  icon: Icons.language_outlined,
                  value: _selectedLanguage,
                  items: ['বাংলা', 'English'],
                  onChanged: (val) => setState(() => _selectedLanguage = val!),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildNumberInput(
                  label: 'Questions Count',
                  icon: Icons.format_list_numbered,
                  controller: _countController,
                  onChanged: (val) => setState(() {}),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildNumberInput({
    required String label,
    required IconData icon,
    required TextEditingController controller,
    required ValueChanged<String> onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: TextStyle(fontSize: 12, color: Colors.grey.shade600)),
        const SizedBox(height: 4),
        Container(
          height: 48,
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            color: Colors.grey.shade50,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.grey.shade200),
          ),
          child: TextField(
            controller: controller,
            keyboardType: TextInputType.number,
            textAlign: TextAlign.center,
            inputFormatters: [FilteringTextInputFormatter.digitsOnly],
            onChanged: onChanged,
            decoration: const InputDecoration(
              border: InputBorder.none,
              contentPadding: EdgeInsets.zero,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String label,
    required IconData icon,
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: TextStyle(fontSize: 12, color: Colors.grey.shade600)),
        const SizedBox(height: 4),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            color: Colors.grey.shade50,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.grey.shade200),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              isExpanded: true,
              value: value,
              alignment: Alignment.center,
              icon: Icon(Icons.keyboard_arrow_down, color: Colors.teal.shade600),
              items: items.map((e) => DropdownMenuItem(
                value: e, 
                child: Center(child: Text(e))
              )).toList(),
              onChanged: onChanged,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildInstructionSection() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Step 2: Copy Instruction',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 12),
          const Text(
            'Use this instruction in your third-party AI app (like ChatGPT, Gemini) to generate the JSON from your images.',
            style: TextStyle(fontSize: 14, color: Colors.black87),
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.grey.shade100,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.grey.shade300),
            ),
            child: Text(
              _getCustomInstruction(),
              style: const TextStyle(fontFamily: 'monospace', fontSize: 12),
            ),
          ),
          const SizedBox(height: 16),
          ElevatedButton.icon(
            onPressed: _copyToClipboard,
            icon: const Icon(Icons.copy_outlined, size: 18),
            label: const Text('Copy Instruction'),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.teal.shade600,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 20),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInputSection() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Step 3: Paste JSON',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _jsonController,
            maxLines: 8,
            decoration: InputDecoration(
              hintText: 'Paste the JSON response here...',
              fillColor: Colors.grey.shade50,
              filled: true,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: Colors.grey.shade300),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: Colors.grey.shade300),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: Colors.teal.shade400, width: 2),
              ),
            ),
            style: const TextStyle(fontFamily: 'monospace', fontSize: 13),
          ),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              TextButton.icon(
                onPressed: _pasteFromClipboard,
                icon: const Icon(Icons.paste_outlined, size: 18),
                label: const Text('Paste'),
                style: TextButton.styleFrom(
                  foregroundColor: Colors.teal.shade600,
                ),
              ),
              const SizedBox(width: 8),
              TextButton.icon(
                onPressed: () => _jsonController.clear(),
                icon: const Icon(Icons.clear_all, size: 18),
                label: const Text('Clear'),
                style: TextButton.styleFrom(
                  foregroundColor: Colors.red.shade600,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildActionButton() {
    return Container(
      height: 56,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Colors.teal.shade600, Colors.teal.shade800],
        ),
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.teal.withOpacity(0.3),
            blurRadius: 12,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: ElevatedButton(
        onPressed: _buildTest,
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.transparent,
          foregroundColor: Colors.white,
          shadowColor: Colors.transparent,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
        child: const Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.rocket_launch_outlined),
            SizedBox(width: 12),
            Text(
              'Build Test',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
          ],
        ),
      ),
    );
  }
}
